apiVersion: apps/v1

kind: Deployment

metadata:
  name: {{ .Release.Name }}

spec:

  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Release.Name }}

  template:

    metadata:
      labels:
        app: {{ .Release.Name }}

    spec:

      containers:

      - name: employee-directory

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:

        - containerPort: {{ .Values.containerPort }}

        resources:
          {{- toYaml .Values.resources | nindent 10 }}

        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.containerPort }}

          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.containerPort }}

          initialDelaySeconds: 10
          periodSeconds: 20
